### ISSUE TITLE
Deleting Joined and Invited messages 

### ISSUE THREAD

**Issue by TalEliyahu** [Singapore-Tech-Entrepreneurs/BossBot.io#1]

**Comment by TalEliyahu** [comment]
Deleting left messages

**Comment by TalEliyahu** [comment]
Once the bot joined it will also delete all previous messages like this for people that left, joined or invited

**Comment by ichi404gh** [comment]
> Deleting left messages

Was implemented with option to enable/disable filtering

> Once the bot joined it will also delete all previous messages like this for people that left, joined or invited

Not sure that is possible at all. Bots have no access to previous history, before they are joined to group.
