### ISSUE TITLE
Settings 

### ISSUE THREAD

**Issue by TalEliyahu** [Singapore-Tech-Entrepreneurs/BossBot.io#17]
General group settings

/config or  /settings: manage the group settings in private from an inline keyboard.
The inline keyboard has six sub-menus:

Menu: manage the most important group settings
Antiflood: turn on or off the antiflood, set its sensitivity and choose some media to ignore, if you want
Media: choose which media to forbid in your group, and set the number of times that an user will be warned before being kicked/banned
Antispam: choose which kind of spam you want to forbid (example: telegram.me links, forwarded messages from channels)
Log channel: choose which updates should be logged
Moderators: promote or demote moderators

Bonus commands:
/reportflood [number of messages]/[timeframe]: set how many times users can use the @admin command within a certain timeframe.
/leave: the bot will leave the group without deleting its data. Use this command only if you are going to add the bot to the group again
/snap: generate a backup file that can be restored with /import (send the file in the group and reply to it). /snap can be used once every three days

**Comment by ichi404gh** [comment]
implemented simple button-like menu for frequent functions, with ability to append new menu items easily
