### ISSUE TITLE
Mongoose models

### ISSUE THREAD

**Issue by AlSoEdit** [Singapore-Tech-Entrepreneurs/BossBot.io#56]
All models logic should be separated from controllers. If controller need to get access to data from DB it should call a short method from model and just send the response.

To do it all manipulations with mongoose should be encapsulated inside modules which work only with DB data. Models should be described in Schema-style: [docs](http://mongoosejs.com/docs/guide.html). That way of presentation of data will give better understanding of what fields model (table) consists of. Also it will be easier to set validators and constraints on fields when it define through model. Additionally, you can write static\dynamic methods for the model, which will give you an opportunity to encapsulate complicated interactions with data.

In the result you will have fat models modules and thin controllers. Splitting models and controllers like this will help you to test models and controllers logic independently from each other.

**Comment by kryptome** [comment]
All the Model Logic has now been Shifted to static methods to the particular Models. Also, there is minimum logic used in Controller, to make it easier for anyone to write test cases.
